### ISSUE TITLE
Where do the files go?

### ISSUE THREAD

**Issue by walmartwarlord** [crazy-max/ghaction-xgo#251]
Hi, where do the files actually go? I have set up my github action and on push it builds successfully and the target folder is `build` (default) but I don't see any binary file somewhere on my repository? Should I run this setup locally on my PC?

I am using M1 Mac Pro locally.

Thank you for this!

**Comment by slashtechno** [comment]
I suspect it may be `/build`. I couldn't find it either initially. I suggest you set your destination to `/home/runner/work/repo-name/builds`

**Comment by crazy-max** [comment]
What's defined by [`dest` input](https://github.com/crazy-max/ghaction-xgo#inputs) (defaults to `build` in your workspace)
