### ISSUE TITLE
Error: Unexpected HTTP response: 404

### ISSUE THREAD

**Issue by zijiren233** [crazy-max/ghaction-xgo#259]
![image](https://user-images.githubusercontent.com/84728412/212291550-71513a52-257f-4164-ad7e-c87f83d3169a.png)

![image](https://user-images.githubusercontent.com/84728412/212291471-c57b45dd-5cb8-44a1-8c76-fa987bdd25be.png)

how to fix

**Comment by crazy-max** [comment]
This is fixed in https://github.com/crazy-max/ghaction-xgo/pull/258 but forgot to create a release. Will do that.

**Comment by crazy-max** [comment]
@zijiren233 Should be good
