### ISSUE TITLE
Not producing binaries for mobiles

### ISSUE THREAD

**Issue by CaiMiao** [crazy-max/ghaction-xgo#77]
I tried to build with your Action and result is below:
https://github.com/346lab/v2ray-core/actions/runs/41329809

Notice that when I used `-x` param and there was no more verbosed outputs.
`Build/` is also empty.

Also it's reported that original `xgo` is working for vanilla git repo (where I forked from) .

---

~~I'm also requesting to add support for original `-tag` param passing since one submodule needs that param.~~

**Comment by crazy-max** [comment]
@CaiMiao 

This action uses [crazy-max/xgo](https://github.com/crazy-max/xgo) Docker image and support for `ios/*` and `android/*` has been removed in this one.

> I'm also requesting to add support for original -tag param passing since one submodule needs that param.

Please create one issue per request.

**Comment by CaiMiao** [comment]
> @CaiMiao
> 
> This action uses [crazy-max/xgo](https://github.com/crazy-max/xgo) Docker image and support for `ios/*` and `android/*` has been removed in this one.
> 
> > I'm also requesting to add support for original -tag param passing since one submodule needs that param.
> 
> Please create one issue per request.

any chance to include it again/in a new branch?

**Comment by crazy-max** [comment]
@CaiMiao Don't think so but feel free to open a PR on [crazy-max/xgo](https://github.com/crazy-max/xgo) to bring it back.
